### ISSUE TITLE
Where is the image saved?

### ISSUE THREAD

**Issue by innocenzi** [cvuorinen/raspicam-php#3]
Hi,
I'm kinda new to Raspberry, and I am trying to create a web interface for my camera.
This project looked good and clean, but I am not able to use it as I don't know how to make it work.

I am using the example method:

```php
require 'vendor/autoload.php';
use Cvuorinen\Raspicam\Raspistill;

$camera = new Raspistill([
    'timeout' => 1,
    'rotate' => 90,
    'exposure' => Raspistill::EXPOSURE_NIGHT,
    'quality' => 85,
]);

$camera->takePicture('pic.jpg');
```

But I can't find any `pic.jpg` file and I don't get any error.
May you help me?

Thanks

**Comment by cvuorinen** [comment]
It might be a permission issue. The user you are executing the script with needs permission to `/dev/vchiq` as well as the directory where the image would be saved to.

The filename is relative to the current working directory of the php script, but you can also use an absolute path (e.g. `/tmp/pic.jpg`).

Are you executing the php script from command-line or through a web server like Apache? With Apache the user that the script is executed with is `www-data`, so you need to make sure that it has correct permissions. Permission to `/dev/vchiq` can be granted by adding the user to the group `video`, which has the necessary permission. In case of Apache, it can be done using command: `sudo usermod -a -G video www-data`. The default user `pi` should already belong to this group and thus have permission, but if you are executing from command-line with some other user, you need to add that user to the group as well.

If you are not executing straight from command-line, you should also check the web server error logs for any errors. If you see an `Unknown or custom error`, then it might be useful to try executing raspistill without raspicam-php wrapper first to get the full command output by creating a PHP file with just:
```php
<?php
passthru("raspistill -v -o /tmp/test.jpg");
```

Let me know if you are able to get it working or if you run into more issues. I will add a troubleshooting section to the readme with common issues.

**Comment by innocenzi** [comment]
It was indeed a permission issue. I have been able to fix it before your reply, but I learned from what you said. Thank you.

Good idea for the troubleshooting section.
